/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package minerofmillions.factorio

import kotlin.test.Test

class RecipeManagerTest {
    @Test
    fun testAppHasAGreeting() {
    }
}
